/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httpassignmentclient;

import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modules.Product;

/**
 *
 * @author masri
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(HTTPAssignmentClient client, Date lastLogin, String employeeID) {
        initComponents();
        this.client = client;
        this.lastLogin = lastLogin;
        this.employeeID = employeeID;
        this.employeeIDLbl.setText("Employee ID: " + employeeID);
        this.lastLoginLbl.setText("Last Login: " + lastLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        employeeIDLbl = new javax.swing.JLabel();
        lastLoginLbl = new javax.swing.JLabel();
        changePasswordTFBTN = new javax.swing.JButton();
        showAllProductsBtn = new javax.swing.JButton();
        lookupProductBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        productPnl = new javax.swing.JPanel();
        waitingLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeIDLbl.setText("Employee ID: 118");

        lastLoginLbl.setText("Last Login: 6/5/2020 8PM");

        changePasswordTFBTN.setText("Change Password");
        changePasswordTFBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordTFBTNMouseClicked(evt);
            }
        });
        changePasswordTFBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordTFBTNActionPerformed(evt);
            }
        });

        showAllProductsBtn.setText("Show all products");
        showAllProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllProductsBtnMouseClicked(evt);
            }
        });
        showAllProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllProductsBtnActionPerformed(evt);
            }
        });

        lookupProductBtn.setText("Look up product");
        lookupProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lookupProductBtnMouseClicked(evt);
            }
        });
        lookupProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupProductBtnActionPerformed(evt);
            }
        });

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        productPnl.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeIDLbl)
                            .addComponent(lastLoginLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changePasswordTFBTN)
                                .addGap(63, 63, 63)
                                .addComponent(waitingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showAllProductsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lookupProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeIDLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastLoginLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(showAllProductsBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(changePasswordTFBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lookupProductBtn)
                            .addComponent(waitingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(insertBtn)
                        .addGap(39, 39, 39)
                        .addComponent(withdrawBtn))
                    .addComponent(productPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void changePasswordTFBTNActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        ChangePasswordFrame f = new ChangePasswordFrame(client, employeeID);
        f.setLocationRelativeTo(this);
        f.setVisible(true);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }                                                   

    private void showAllProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        ArrayList<Product> products = client.showAllProducts();
        if (products.size() == 0) {
            JOptionPane.showMessageDialog(this, "No products to show", "No Products", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ProductsFrame pf = new ProductsFrame(products);
        pf.setTitle("Products");
        pf.setLocationRelativeTo(this);
        pf.setVisible(true);
    }                                                  

    private void lookupProductBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.productPnl.removeAll();
        String id = JOptionPane.showInputDialog(this, "Pleases enter the product id");
        if (id == null) {
            return;
        }
        Product p = client.lookUpProduct(id);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No product with the entered id exists", "No product found", JOptionPane.ERROR_MESSAGE);
        } else {
            this.productPnl.add(new ProductPanel(p));
            this.productPnl.getComponent(0).setVisible(false);
            this.productPnl.getComponent(0).setVisible(true);
        }
    }                                                

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        InsertFrame insertFrame = new InsertFrame(client);
        insertFrame.setTitle("Insert Product");
        insertFrame.setLocationRelativeTo(this);
        insertFrame.setVisible(true);
    }                                         

    private void changePasswordTFBTNMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        // TODO add your handling code here:
//        this.newPasswordLbl.setVisible(true);
//        this.newPasswordTF.setVisible(true);
//        this.changePasswordBtn.setVisible(true);
    }                                                

    private void showAllProductsBtnMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:

    }                                               

    private void lookupProductBtnMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        JTextField t = new JTextField("stting");
        this.add(t);
    }                                             

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        WithdrawFrame withdrawFrame = new WithdrawFrame(client);
        withdrawFrame.setTitle("Withdraw Product");
        withdrawFrame.setLocationRelativeTo(this);
        withdrawFrame.setVisible(true);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(new HTTPAssignmentClient(), new Date(), "").setVisible(true);
            }
        });
    }
    private HTTPAssignmentClient client;
    private Date lastLogin;
    private String employeeID;
    // Variables declaration - do not modify                     
    private javax.swing.JButton changePasswordTFBTN;
    private javax.swing.JLabel employeeIDLbl;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel lastLoginLbl;
    private javax.swing.JButton lookupProductBtn;
    private javax.swing.JPanel productPnl;
    private javax.swing.JButton showAllProductsBtn;
    private javax.swing.JLabel waitingLbl;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration                   

    private PopupMenu JLabel(String waiting) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
