/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package httpassignmentclient;

import java.text.DecimalFormat;
import modules.Product;

/**
 *
 * @author masri
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductsPnl
     */
    public ProductPanel(Product product) {
        initComponents();
        this.product = product;
        this.productIDLbl.setText("Product ID               : "+product.getId());
        this.productNameLbl.setText("Product Name        : "+product.getName());
        this.priceUSDLbl.setText("Price / item (USD)  : "+product.getPricePerItem()+" $");
        DecimalFormat numberFormat = new DecimalFormat("#.000");
        this.priceEURLbl.setText("Price / item (EUR)  : "+numberFormat.format(product.getPricePerItemEUR())+" €");
        this.amountLbl.setText("Amount in stock     : "+product.getAmount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        productIDLbl = new javax.swing.JLabel();
        priceUSDLbl = new javax.swing.JLabel();
        priceEURLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        productNameLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(100, 100));

        productIDLbl.setText("Product ID             : ");

        priceUSDLbl.setText("Price / item (USD)  : ");

        priceEURLbl.setText("Price / item (EUR)  : ");

        amountLbl.setText("Amount in stock     : ");

        productNameLbl.setText("Product Name        : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productIDLbl)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceEURLbl)
                            .addComponent(priceUSDLbl)
                            .addComponent(amountLbl)
                            .addComponent(productNameLbl))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(productIDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceUSDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceEURLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
    }// </editor-fold>                        

    private Product product;
    // Variables declaration - do not modify                     
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel priceEURLbl;
    private javax.swing.JLabel priceUSDLbl;
    private javax.swing.JLabel productIDLbl;
    private javax.swing.JLabel productNameLbl;
    // End of variables declaration                   
}
